version: '3.8'

services:
  database:
    build:
      context: ./Database
      dockerfile: Dockerfile
    image: dacpac-image
    container_name: pfm-db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!Passw0rd
    ports:
      - "1433:1433"
    networks:
      - app-network
    restart: unless-stopped

  webapi:
    build:
      context: ./
      dockerfile: ./WebApi/Dockerfile
    image: webapi-image
    container_name: pfm-webapi
    environment:  
      - ConnectionStrings__DefaultConnection=Server=database;Database=PersonalFinanceManager;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;Encrypt=False;
      - ASPNETCORE_ENVIRONMENT=DEVELOPMENT
    ports:
      - "5000:80"
      - "5001:443"
      - "5002:8081"
    depends_on:
      - database
    networks:
      - app-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    image: pfm-frontend
    container_name: pfm-frontend
    ports:
      - "3000:3000"  # frontend na localhost:3000
    networks:
      - app-network
    depends_on:
      - webapi


networks:
  app-network:
    driver: bridge
