CREATE TABLE [dbo].[AppUser]
(
    [Id] INT NOT NULL IDENTITY,
    [Login] NVARCHAR(200) NOT NULL,
    [Email] NVARCHAR(200) NOT NULL,
    [PasswordHash] NVARCHAR(256) NOT NULL, -- unikamy MAX
    [DefaultCurrency] NVARCHAR(20) NOT NULL DEFAULT 'PLN',
    [GoogleId] NVARCHAR(200) NULL,
    [CreatedAt] DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    PRIMARY KEY NONCLUSTERED ([Id]) NOT ENFORCED
);
GO
